/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPanel: typeof import('./src/components/welfare/AdminPanel.vue')['default']
    ApplicationPanel: typeof import('./src/components/welfare/ApplicationPanel.vue')['default']
    AuthPanel: typeof import('./src/components/welfare/AuthPanel.vue')['default']
    DashboardLayout: typeof import('./src/components/welfare/DashboardLayout.vue')['default']
    HeroPanel: typeof import('./src/components/welfare/HeroPanel.vue')['default']
    PageShell: typeof import('./src/components/welfare/PageShell.vue')['default']
    ProfilePanel: typeof import('./src/components/welfare/ProfilePanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/welfare/SideNav.vue')['default']
    SiteHeader: typeof import('./src/components/welfare/SiteHeader.vue')['default']
    StudentPanel: typeof import('./src/components/welfare/StudentPanel.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
