/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPanel: typeof import('./src/components/welfare/AdminPanel.vue')['default']
    ApplicationCreatePanel: typeof import('./src/components/welfare/ApplicationCreatePanel.vue')['default']
    ApplicationDetailPanel: typeof import('./src/components/welfare/ApplicationDetailPanel.vue')['default']
    ApplicationPanel: typeof import('./src/components/welfare/ApplicationPanel.vue')['default']
    ApplicationResultSubmit: typeof import('./src/components/welfare/ApplicationResultSubmit.vue')['default']
    ApplicationThread: typeof import('./src/components/welfare/ApplicationThread.vue')['default']
    AuthPanel: typeof import('./src/components/welfare/AuthPanel.vue')['default']
    DashboardLayout: typeof import('./src/components/welfare/DashboardLayout.vue')['default']
    DataNotice: typeof import('./src/components/welfare/DataNotice.vue')['default']
    HeroPanel: typeof import('./src/components/welfare/HeroPanel.vue')['default']
    HomeOverviewPanel: typeof import('./src/components/welfare/HomeOverviewPanel.vue')['default']
    MarkdownEditor: typeof import('./src/components/welfare/MarkdownEditor.vue')['default']
    NotificationSettingsPanel: typeof import('./src/components/welfare/NotificationSettingsPanel.vue')['default']
    NotificationsPanel: typeof import('./src/components/welfare/NotificationsPanel.vue')['default']
    OpenSourcePanel: typeof import('./src/components/welfare/OpenSourcePanel.vue')['default']
    PageShell: typeof import('./src/components/welfare/PageShell.vue')['default']
    ProfilePanel: typeof import('./src/components/welfare/ProfilePanel.vue')['default']
    ReviewQueues: typeof import('./src/components/welfare/ReviewQueues.vue')['default']
    RichTextEditor: typeof import('./src/components/welfare/RichTextEditor.vue')['default']
    RichTextView: typeof import('./src/components/welfare/RichTextView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/welfare/SideNav.vue')['default']
    SiteHeader: typeof import('./src/components/welfare/SiteHeader.vue')['default']
    SquarePanel: typeof import('./src/components/welfare/SquarePanel.vue')['default']
    StudentCreatePanel: typeof import('./src/components/welfare/StudentCreatePanel.vue')['default']
    StudentPanel: typeof import('./src/components/welfare/StudentPanel.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TurnstileChallenge: typeof import('./src/components/welfare/TurnstileChallenge.vue')['default']
    VerificationPanel: typeof import('./src/components/welfare/VerificationPanel.vue')['default']
    WalletPanel: typeof import('./src/components/welfare/WalletPanel.vue')['default']
  }
}
