/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/'
      | '/dashboard/admin'
      | '/dashboard/apply'
      | '/dashboard/profile'
      | '/dashboard/student'
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/admin': RouteRecordInfo<
      '/dashboard/admin',
      '/dashboard/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/apply': RouteRecordInfo<
      '/dashboard/apply',
      '/dashboard/apply',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/profile': RouteRecordInfo<
      '/dashboard/profile',
      '/dashboard/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/student': RouteRecordInfo<
      '/dashboard/student',
      '/dashboard/student',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hi/[name]': RouteRecordInfo<
      '/hi/[name]',
      '/hi/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
        | '/dashboard/'
        | '/dashboard/admin'
        | '/dashboard/apply'
        | '/dashboard/profile'
        | '/dashboard/student'
      views:
        | 'default'
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/admin.vue': {
      routes:
        | '/dashboard/admin'
      views:
        | never
    }
    'src/pages/dashboard/apply.vue': {
      routes:
        | '/dashboard/apply'
      views:
        | never
    }
    'src/pages/dashboard/profile.vue': {
      routes:
        | '/dashboard/profile'
      views:
        | never
    }
    'src/pages/dashboard/student.vue': {
      routes:
        | '/dashboard/student'
      views:
        | never
    }
    'src/pages/hi/[name].vue': {
      routes:
        | '/hi/[name]'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
